# Generated by Django 4.0.1 on 2022-01-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('department', models.CharField(choices=[('SL', 'Sales'), ('PD', 'Products')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dastetime_begin', models.DateTimeField(max_length=255)),
                ('datetime_end', models.DateTimeField(max_length=255)),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_room_booking.meetingroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_room_booking.user')),
            ],
        ),
    ]
