# Generated by Django 4.0.1 on 2022-01-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dastetime_begin',
            new_name='datetime_begin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
