# Generated by Django 4.0.1 on 2022-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0002_rename_dastetime_begin_booking_datetime_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
